name: trust

include:
  - ../service/network/traefik/docker-compose.yaml
  - ../service/network/tsdproxy/docker-compose.yaml
  - ../service/monitoring/docker-compose.yaml
  - ../service/teslamate/docker-compose.yaml
  - ../service/dashboard/local/docker-compose.yaml
