name: trust

include:
  - ../service/network/traefik/docker-compose.yaml
  - ../service/network/tsdproxy/docker-compose.yaml
  - ../service/monitoring/docker-compose.yaml
  - ../service/budget/docker-compose.yaml
  - ../service/karakeep/docker-compose.yaml
  - ../service/librespeed/docker-compose.yaml
  - ../service/llama-ui/docker-compose.yaml
  - ../service/mealie/docker-compose.yaml
  - ../service/pdf/docker-compose.yaml
  - ../service/teslamate/docker-compose.yaml
  - ../service/dashboard/local/docker-compose.yaml
