#!/usr/bin/env bash
set -euo pipefail

die() {
  echo "Error: $*" >&2
  exit 1
}

usage() {
  cat <<'EOF'
Usage:
  doppler-compose.sh [start|stop|list|generate|help]

Commands:
  start      Generate configs, refresh auth key, and run docker compose up -d (default)
  stop       Stop and remove the stack (docker compose down)
  list       Show running stack services (docker compose ps)
  generate   Generate Homepage and Gatus configs only
  help       Show this help
EOF
}

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
TRUST_DIR="$(cd -- "$SCRIPT_DIR/.." && pwd)"
STACK_DIR="$SCRIPT_DIR"

INVENTORY_PATH="$TRUST_DIR/service/common/services.inventory.json"
HOMEPAGE_PATH="$TRUST_DIR/service/dashboard/local/homepage/services.yaml"
GATUS_PATH="$TRUST_DIR/service/monitoring/config/config.yaml"
AUTH_FILE="$TRUST_DIR/ts_authkey"

require_docker() {
  command -v docker >/dev/null 2>&1 || die "docker is not installed or not in PATH"
  docker compose version >/dev/null 2>&1 || die "docker compose (v2) is not available"
}

require_doppler() {
  command -v doppler >/dev/null 2>&1 || die "doppler is not installed or not in PATH"
}

enter_stack_dir() {
  cd "$STACK_DIR" || die "failed to cd into $STACK_DIR"
  if [[ ! -f docker-compose.yaml && ! -f docker-compose.yml ]]; then
    die "no docker-compose.yaml or docker-compose.yml found in $STACK_DIR"
  fi
}

generate_configs() {
  command -v jq >/dev/null 2>&1 || die "jq is required but not installed"
  [[ -f "$INVENTORY_PATH" ]] || die "inventory file not found: $INVENTORY_PATH"

  mkdir -p "$(dirname "$HOMEPAGE_PATH")" "$(dirname "$GATUS_PATH")"

  local tmp_homepage tmp_gatus
  tmp_homepage="$(mktemp)"
  tmp_gatus="$(mktemp)"
  trap 'rm -f "$tmp_homepage" "$tmp_gatus"' RETURN

  cat >"$tmp_homepage" <<'EOF'
---
# Generated by trust/stack/doppler-compose.sh generate
# Source of truth: trust/service/common/services.inventory.json

EOF

  jq -r '
    def homepage_enabled: if has("homepageEnabled") then .homepageEnabled else true end;
    def homepage_name: (.homepageName // .name);
    (
      .services
      | map(select(homepage_enabled == true))
      | sort_by(.homepageGroup, homepage_name)
      | group_by(.homepageGroup)
      | map(
          "- \(.[0].homepageGroup):\n"
          + (map("    - \(homepage_name):\n        href: \(.url)") | join("\n"))
        )
      | join("\n\n")
    )
  ' "$INVENTORY_PATH" >>"$tmp_homepage"

  jq -r '
    . as $root
    | def monitor_enabled: if has("monitorEnabled") then .monitorEnabled else true end;
    def monitor_name: (.monitorName // .name);
    def monitor_url: (.monitorUrl // (if .monitorPath then (.url + .monitorPath) else .url end));
    def monitor_group: (.monitorGroup // ((.homepageGroup // "internal") | ascii_downcase));
    "storage:\n  type: postgres\n  path: \($root.gatus.storagePath)\n\n"
    + "ui:\n  title: \($root.gatus.ui.title)\n  description: \($root.gatus.ui.description)\n\n"
    + "endpoints:\n\n"
    + (
        $root.services
        | map(select(monitor_enabled == true))
        | sort_by(monitor_group, monitor_name)
        | map(
            "  - name: \(monitor_name)\n"
            + "    group: \(monitor_group)\n"
            + "    url: \(monitor_url)\n"
            + "    interval: \(.monitorInterval // $root.gatus.defaults.interval)\n"
            + "    conditions:\n"
            + (
                (.monitorConditions // $root.gatus.defaults.conditions)
                | map("      - \"" + . + "\"")
                | join("\n")
              )
          )
        | join("\n")
      )
  ' "$INVENTORY_PATH" >"$tmp_gatus"

  mv "$tmp_homepage" "$HOMEPAGE_PATH"
  mv "$tmp_gatus" "$GATUS_PATH"

  echo "Generated:"
  echo "  - $HOMEPAGE_PATH"
  echo "  - $GATUS_PATH"
}

fetch_auth_key() {
  require_doppler

  local tmp_auth_file
  tmp_auth_file="$(mktemp "${AUTH_FILE}.tmp.XXXXXX")"
  trap 'rm -f "$tmp_auth_file"' RETURN

  doppler secrets get TAILSCALE_AUTH_KEY -p homelab -c dev --plain >"$tmp_auth_file" \
    || die "failed to read TAILSCALE_AUTH_KEY from Doppler"

  mv "$tmp_auth_file" "$AUTH_FILE" || die "failed to write auth key to $AUTH_FILE"
  chmod 600 "$AUTH_FILE" || die "failed to set permissions on $AUTH_FILE"
}

start_stack() {
  require_docker
  enter_stack_dir
  generate_configs
  fetch_auth_key
  doppler run -c dev -p homelab -- docker compose up -d
}

stop_stack() {
  require_docker
  enter_stack_dir
  doppler run -c dev -p homelab -- docker compose down
}

list_stack() {
  require_docker
  enter_stack_dir
  doppler run -c dev -p homelab -- docker compose ps
}

action="${1:-start}"
case "$action" in
  start)
    start_stack
    ;;
  stop)
    stop_stack
    ;;
  list)
    list_stack
    ;;
  generate)
    generate_configs
    ;;
  help|-h|--help)
    usage
    ;;
  *)
    die "unknown command: $action (use: start, stop, list, generate, help)"
    ;;
esac
