apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karakeep-data-pvc
  namespace: karakeep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-nvme-client
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: karakeep-meili-pvc
  namespace: karakeep
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-nvme-client
  resources:
    requests:
      storage: 10Gi