#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
INVENTORY_PATH="${1:-$ROOT_DIR/service/common/services.inventory.json}"
HOMEPAGE_PATH="$ROOT_DIR/service/dashboard/local/homepage/services.yaml"
GATUS_PATH="$ROOT_DIR/service/monitoring/config/config.yaml"

die() {
  echo "Error: $*" >&2
  exit 1
}

command -v jq >/dev/null 2>&1 || die "jq is required but not installed"
[[ -f "$INVENTORY_PATH" ]] || die "inventory file not found: $INVENTORY_PATH"

mkdir -p "$(dirname "$HOMEPAGE_PATH")" "$(dirname "$GATUS_PATH")"

tmp_homepage="$(mktemp)"
tmp_gatus="$(mktemp)"
cleanup() {
  rm -f "$tmp_homepage" "$tmp_gatus"
}
trap cleanup EXIT

cat >"$tmp_homepage" <<'EOF'
---
# Generated by trust/scripts/generate-service-configs.sh
# Source of truth: trust/service/common/services.inventory.json

EOF

jq -r '
  def homepage_enabled: if has("homepageEnabled") then .homepageEnabled else true end;
  def homepage_name: (.homepageName // .name);
  (
    .services
    | map(select(homepage_enabled == true))
    | sort_by(.homepageGroup, homepage_name)
    | group_by(.homepageGroup)
    | map(
        "- \(.[0].homepageGroup):\n"
        + (map("    - \(homepage_name):\n        href: \(.url)") | join("\n"))
      )
    | join("\n\n")
  )
' "$INVENTORY_PATH" >>"$tmp_homepage"

jq -r '
  . as $root
  | def monitor_enabled: if has("monitorEnabled") then .monitorEnabled else true end;
  def monitor_name: (.monitorName // .name);
  def monitor_url: (.monitorUrl // (if .monitorPath then (.url + .monitorPath) else .url end));
  def monitor_group: (.monitorGroup // ((.homepageGroup // "internal") | ascii_downcase));
  "storage:\n  type: postgres\n  path: \($root.gatus.storagePath)\n\n"
  + "ui:\n  title: \($root.gatus.ui.title)\n  description: \($root.gatus.ui.description)\n\n"
  + "endpoints:\n\n"
  + (
      $root.services
      | map(select(monitor_enabled == true))
      | sort_by(monitor_group, monitor_name)
      | map(
          "  - name: \(monitor_name)\n"
          + "    group: \(monitor_group)\n"
          + "    url: \(monitor_url)\n"
          + "    interval: \(.monitorInterval // $root.gatus.defaults.interval)\n"
          + "    conditions:\n"
          + (
              (.monitorConditions // $root.gatus.defaults.conditions)
              | map("      - \"" + . + "\"")
              | join("\n")
            )
        )
      | join("\n")
    )
' "$INVENTORY_PATH" >"$tmp_gatus"

mv "$tmp_homepage" "$HOMEPAGE_PATH"
mv "$tmp_gatus" "$GATUS_PATH"

echo "Generated:"
echo "  - $HOMEPAGE_PATH"
echo "  - $GATUS_PATH"
