configs:
  tsdproxy_static:
    file: tsdproxy.yaml
  tsdproxy_authkey:
    file: ../../../ts_authkey

services:
  tsdproxy:
    image: almeidapaulopt/tsdproxy:1.4.7
    configs:
      - source: tsdproxy_static
        target: /config/tsdproxy.yaml
      - source: tsdproxy_authkey
        target: /run/secrets/ts_authkey
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - tsdproxy_state:/data
    command:
      - /config/tsdproxy.yaml
    networks:
      - traefik-public
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      restart_policy:
        condition: on-failure

networks:
  traefik-public:
    external: true
    name: traefik-public

volumes:
  tsdproxy_state: