storage:
  type: postgres
  path: postgres://${PG_USER}:${PG_PASS}@${PG_HOST}:5432/gatus?sslmode=disable

ui:
  title: Homelab Monitoring
  description: Internal service health checks

endpoints:

  - name: PDF Service
    group: internal
    url: http://pdf.local/login
    interval: 30s
    conditions:
      - "[STATUS] == 200"
  - name: Teslamate Service
    group: internal
    url: http://teslamate.local
    interval: 30s
    conditions:
      - "[STATUS] == 200"
  - name: Teslamate Grafana Service
    group: internal
    url: http://teslamate-grafana.local/login
    interval: 30s
    conditions:
      - "[STATUS] == 200"