storage:
  type: postgres
  path: postgres://${PG_USER}:${PG_PASS}@${PG_HOST}:5432/gatus?sslmode=disable

ui:
  title: Homelab Monitoring
  description: Internal service health checks

endpoints:

  - name: TSDProxy
    group: infrastructure
    url: http://tailscale.local
    interval: 30s
    conditions:
      - "[STATUS] == 200"
  - name: Budget
    group: internal
    url: http://budget.local
    interval: 30s
    conditions:
      - "[STATUS] == 200"
  - name: Llama UI
    group: internal
    url: http://llama-ui.local
    interval: 30s
    conditions:
      - "[STATUS] == 200"
  - name: PDF
    group: internal
    url: http://pdf.local/login
    interval: 30s
    conditions:
      - "[STATUS] == 200"
  - name: Recipes
    group: internal
    url: http://recipes.local
    interval: 30s
    conditions:
      - "[STATUS] == 200"
  - name: Speedtest
    group: internal
    url: http://speedtest.local
    interval: 30s
    conditions:
      - "[STATUS] == 200"
  - name: Teslamate Grafana Service
    group: internal
    url: http://teslamate-grafana.local/login
    interval: 30s
    conditions:
      - "[STATUS] == 200"
  - name: Teslamate Service
    group: internal
    url: http://teslamate.local
    interval: 30s
    conditions:
      - "[STATUS] == 200"
