apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: tailscale
  namespace: flux-system
spec:
  interval: 1h
  url: https://pkgs.tailscale.com/helmcharts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 10m
  chart:
    spec:
      chart: tailscale-operator
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: flux-system
  valuesFrom:
    - kind: Secret
      name: secrets
      valuesKey: TAILSCALE_CLIENT_ID
      targetPath: oauth.clientId
    - kind: Secret
      name: secrets
      valuesKey: TAILSCALE_CLIENT_SECRET
      targetPath: oauth.clientSecret