services:
  ollama:
    image: ollama/ollama:0.23.0
    restart: unless-stopped
    runtime: nvidia
    ports:
      - "11434:11434"
    environment:
      TZ: Europe/Copenhagen
      HOST_OS: Unraid
      HOST_HOSTNAME: Homelab
      HOST_CONTAINERNAME: ollama
      OLLAMA_ORIGINS: "*"
      CA_TS_FALLBACK_DIR: /root/.ollama
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIES: all
    labels:
      tsdproxy.enable: "true"
      tsdproxy.name: "ollama"
      tsdproxy.ephemeral: "true"
      tsdproxy.container_port: "11434"
      net.unraid.docker.managed: "dockerman"
      net.unraid.docker.webui: "http://[IP]:[PORT:11434]/"
      net.unraid.docker.icon: "https://ollama.ai/public/ollama.png"
    volumes:
      - "${PATH_APPDATA_UNRAID}/ollama:/root/.ollama"
