apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: teslamate-import
  namespace: teslamate
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-nvme-client
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: teslamate
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-nvme-client
  resources:
    requests:
      storage: 10Gi