apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: homepage-config-pvc
  namespace: homepage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-nvme-client
  resources:
    requests:
      storage: 2Gi