apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data-pvc
  namespace: n8n
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-nvme-client
  resources:
    requests:
      storage: 10Gi

