apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: postgres-superuser
  namespace: postgres
spec:
  encryptedData:
    password: AgBwLAoLuYE9ibKo6+giNwHJYtH5RiB/cJ6CH3Pib4kSBhtQlQDTUjC/WCn5l7vypowvj97pVuikPOY8Fn4JNWmIEhwSDYQtcSO4NTiMhxBmi/NoVsPt9zbJ5/OuOsE5nW19sDhDmMzxSvESgtCa+7szG3LJlbqjb380CnmkxMrLx215Gf94zdddQak5cQaKF2dfGCYMyGP3fput3g6AbUf2tbeyKe736oAVc2CBgy7YJ3sjqZnDEAur9gIrRAPWWmHKMLVQeLHNqp4zuPXuNw24Gjl3O4TDEzZD6CLwwIL7skSbQEZFEbPYRegVYw+xz0LOnEoUeG43y0N3fdW69EmB3e/8L6+Y3aAQbwEHysvEt+k42A9zvPaFeqZtfB8mdLefjfofyA0RauMzkB/kpNP6DfDMbv3r4K0J/86Yo+VWAXhWRpVL4Uc2zRcotf96W9Qx6+kEJUBf3/FVvUG8UIWMkBPLBM0SvBfcK9+Q/IgyaXZVCCrxoTtHVHF17aHtJHL0UgRiPHYkdMCbK38G7bKKB3FRUzS/yfrS9TrgFZD9JGr4co89HmIUgjFUZPy9vl6QQHSOSi3S37uqsOu1zekUNm4HSO6USrOntdJK1bgL+gxv5/g1B5BysmXX6pKA7Zj9a5iD7E5tMD6yvJEMsa0TFB73s1HNAos1U3u0BvYVc56GFkH6iobaBrZdAgQ6Z4MDyaBWynmJJfWGTNmwZwK6zTzqjTRkOxG1/QU=
    username: AgBdCAyn0Q+ca28HDW19zCWxIb/BiXFvbhDI7Jdq0lE+zQZt0Ivro7pFmKTCovizWtoSFhyo+R2FmH2G9eZIQhmLr4FCqvtez4NYNXunRcnmgz8pHDBgJ+z0v5AUlbVDTy3DlaJOBVM+WOUd1i1TNsZgkDyZ2Bxm0SQ7iBkGldBuIsW9VNPBrEPUhvWnrr0L9Q7S+5wFxbwmQU9WHgbfm84CskFWEpPIRQSOHnyN80MhfhwWJne7kE7ZyXr4q4LwT+yVLupfpysLXHaiIyKaRSq7T7kr0zVyCTxdFntEHcXRytVuGxNMuQuDqya7qr5BO+In8wYHSTFYPSTvHuMGRs1FHysSP9sLfvWhwKHDTQNlNWrNb6ADWDifSIa40G4X2rt5FSlugME52ARE2k+9bgEKz6aAgc3pmb2ylR6rW4iRH+pddJ3mQSnQRWg1DV82UKDDHvC+wVgSK4uIQYzn5pC8WN9fTtuffW8tQAbOLSge6uHaGTuRdDdklwgmNrL7ZzIOaDJ6VtyryYftXswSWpa5jki1HpSs5lROcLHazpXZ2UfPEEddfz027lA22KYiu5Fhl1ua9a7Xpqt5ehu034clFWYUkD++Aj5h6pk/tzoX48gEMFmzzAxTYJIGJXAwjYHzYMjJvZkEh1RgjeaXM1hq6U4ewV6zY8cEQtTGNe+hpf8VBRid3wHxN8zqoXS6+0Y55xaJqkvd/Q==
  template:
    metadata:
      creationTimestamp: null
      name: postgres-superuser
      namespace: postgres

