apiVersion: v1
kind: Service
metadata:
  name: shared-postgres-external
  namespace: database
spec:
  type: LoadBalancer
  selector:
    app: shared-postgres
  ports:
    - port: 5432
      targetPort: 5432